### ISSUE TITLE
Use vscode - RestClient for requests

### ISSUE THREAD

**Issue by meysamhadeli** [meysamhadeli/Airline-Microservices#15]

**Comment by gui-com-pt** [comment]
You'll generate the request/response DTOs? I'm facing a deadline situation and the API is already stable, i just run the APIs, open NSwagStudio with the open api .json files of each API pre-opened, generate the outputs classes and copy/paste by hand, once per day it's fine for me.

I'm not sure if i should invest the time to automatize this kind of approach (ex: msbuild, using a task tool) or if it would be better to have it handled with interfaces, would be grateful to to get some advices!

**Comment by meysamhadeli** [comment]
> You'll generate the request/response DTOs? I'm facing a deadline situation and the API is already stable, i just run the APIs, open NSwagStudio with the open api .json files of each API pre-opened, generate the outputs classes and copy/paste by hand, once per day it's fine for me.
> 
> I'm not sure if i should invest the time to automatize this kind of approach (ex: msbuild, using a task tool) or if it would be better to have it handled with interfaces, would be grateful to to get some advices!

No, I will use this extension [vscode-restclinet](https://github.com/Huachao/vscode-restclient). It's like postman and very convenient to use. NSwagStudio has different approach.
