### ISSUE TITLE
Add Blockly for LowCode automation

### ISSUE THREAD

**Issue by ignatandrei** [meysamhadeli/Airline-Microservices#16]
Add https://www.nuget.org/packages/NetCore2Blockly/ to your site - and the site will have LowCode Automation - see https://ignatandrei.github.io/BlocklyAutomation/

**Comment by meysamhadeli** [comment]
Ok. Thanks. I will check it. I think the document of your project in GitHub is not very clear, and I do not understand exactly what it does.

**Comment by ignatandrei** [comment]
It will add LowCode automation to your site - add it and browse to /BlocklyAutomation in your site ( opposed to browsing to /swagger )
